language: node_js
env: CI=true
sudo: false

os:
  - linux
  - osx

node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"

after_script:
  - npm run coverage

notifications:
  email:
    - qiuzhongleiabc@126.com

